#!/usr/bin/env python3
"""Translate /opt/shim/mcp_servers.json (written by codie-injector) into the
TOML shape openhuman-core expects at $OPENHUMAN_WORKSPACE/config.toml.

Schema source: docker-registry/agents/openhuman/src/openhuman/config/schema/tools.rs
(McpServerConfig + McpClientConfig). Specifically the LLM never sees remote
MCP tools as top-level entries; it sees bridge tools `mcp_list_servers` /
`mcp_list_tools` / `mcp_call_tool` and reaches remote tools through them.

Also maps Bridge's BYO-LLM env (OPENAI_BASE_URL / OPENAI_API_KEY / MODEL)
onto core's custom-inference config (`inference_url` / `api_key` /
`default_model`, top-level keys — see config/ops.rs ModelSettingsPatch).
Without these, every chat turn routes to OpenHuman's hosted backend and
dies with SESSION_EXPIRED ("sign in to resume LLM work") because no
OpenHuman account session exists in the container. The internal tier
aliases (reasoning-v1 etc.) fall back to `default_model` on a custom
provider (router.rs tier→hint fallback).

Invoked from supervisor.sh BEFORE `openhuman-core serve` so the daemon
picks up the freshly-written config at startup.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

SRC = Path("/opt/shim/mcp_servers.json")
DST = Path(os.environ.get("OPENHUMAN_WORKSPACE", "/home/openhuman/.openhuman")) / "config.toml"


def _toml_str(s: str) -> str:
    """Minimal TOML basic-string escape — enough for URLs + opaque tokens."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _toml_bool(b: bool) -> str:
    return "true" if b else "false"


def main() -> int:
    # BYO LLM env is independent of the MCP manifest — read it first so a
    # self-host container with a key but no injector still gets configured.
    # Bridge injects the instance's key entry as OPENAI_BASE_URL/
    # OPENAI_API_KEY/MODEL.
    base_url = (os.environ.get("OPENAI_BASE_URL") or "").strip()
    api_key = (os.environ.get("OPENAI_API_KEY") or "").strip()
    model = (os.environ.get("MODEL") or "").strip()
    byo = bool(base_url and api_key)

    payload: dict = {}
    if SRC.is_file():
        try:
            payload = json.loads(SRC.read_text())
        except Exception as exc:
            print(f"[write_config_toml] ERROR parsing {SRC}: {exc}", file=sys.stderr)
            return 1
    elif not byo:
        # No injector AND no BYO key — nothing to write; leave any
        # user-managed config.toml alone.
        print(
            f"[write_config_toml] {SRC} not present and no BYO env, skipping",
            file=sys.stderr,
        )
        return 0

    servers = payload.get("mcp_servers", {}) or {}
    lines: list[str] = [
        "# Auto-generated by /opt/openhuman/write_config_toml.py at container start.",
        "# Edits will be overwritten on next container start — change the source",
        "# at /opt/shim/mcp_servers.json (codie-injector manifest target) instead.",
        "",
    ]

    # BYO LLM (top-level keys — must precede any [section]).
    if byo:
        lines.append(f"inference_url = {_toml_str(base_url)}")
        lines.append(f"api_key = {_toml_str(api_key)}")
        if model:
            lines.append(f"default_model = {_toml_str(model)}")
        lines.append("")
        print(
            f"[write_config_toml] custom inference → {base_url} (model={model or '<unset>'})",
            file=sys.stderr,
        )

    lines += [
        "[mcp_client]",
        f"enabled = {_toml_bool(True)}",
        "",
    ]
    for name, cfg in servers.items():
        endpoint = cfg.get("endpoint") or cfg.get("url") or ""
        enabled = bool(cfg.get("enabled", True))
        timeout = int(cfg.get("timeout_secs", 30))
        token = cfg.get("auth_token") or ""

        lines.append("[[mcp_client.servers]]")
        lines.append(f"name = {_toml_str(name)}")
        lines.append(f"endpoint = {_toml_str(endpoint)}")
        lines.append(f"enabled = {_toml_bool(enabled)}")
        lines.append(f"timeout_secs = {timeout}")
        if token:
            lines.append("")
            lines.append("[mcp_client.servers.auth]")
            lines.append('kind = "bearer_token"')
            lines.append(f"token = {_toml_str(token)}")
        lines.append("")

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(lines))
    print(
        f"[write_config_toml] wrote {len(servers)} MCP server(s) → {DST}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
